services:
  postgres_master:
    image: postgres:16.3
    container_name: postgres_master
    hostname: "primary.postgresql.progressive-web-app"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgresqluser"
      POSTGRES_PASSWORD: "postgresqlpass"
      POSTGRES_DB: "progressive-web-app"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5454:5432
